Models/Payment/BuyViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;

namespace NyxWebPortal.Models.Payment
{
    // You may need to install the Microsoft.AspNetCore.Http.Abstractions package into your project
    public class BuyEventTicketsViewModel
    {
        public string EventId { get; set; }
        public string BotId { get; set; }
        public string StripeTransactionId { get; set; }
        public string Email { get; set; }

        public List<ItemViewModel> Items { get; set; }
    }
}

Models/Payment/PayViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NyxDatabase.Models;

namespace NyxWebPortal.Models.Payment
{
    public class Pay
    {
        public string TransactionId { get; set; }
    }
    
    public class PayViewModel
    {
        public string BotId { get; set; }
        public string BotName { get; set; }
        public string CompanyName { get; set; }
        public string EventId { get; set; }
        public string BotUserId { get; set; }
    }
    
    public class ItemViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public int Sold { get; set; }
        public int Max { get; set; }
        public decimal Price { get; set; }
    }
}

Models/Payment/Transaction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NyxWebPortal.Models.Payment
{
    public class TransactionViewModel
    {
        public string ItemId { get; set; }
        public int Quantity { get; set; }
    }
}

Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NyxDatabase.Data;
using NyxDatabase.Models;
using NyxWebPortal.Models.Payment;
using NyxWebPortal.Services;
using NyxWebPortal.Services.Firebase;
using NyxWebPortal.Utils;

namespace NyxWebPortal.Controllers
{
    public class PaymentController : Controller
    {
        private readonly NyxDbContext _ctx;
        private readonly UserManager<NyxCustomer> _userManager;
        private readonly SignInManager<NyxCustomer> _signInManager;
        private readonly IEmailSender _emailSender;
        private readonly ISmsSender _smsSender;
        private readonly ILogger _logger;
        private readonly CloudinaryService _cloudinary;
        private readonly FirebaseService _firebaseService;

        private const string cloudinaryFolder = "NyxCustomers";

        public PaymentController(
            NyxDbContext ctx,
            UserManager<NyxCustomer> userManager,
            SignInManager<NyxCustomer> signInManager,
            IEmailSender emailSender,
            ISmsSender smsSender,
            ILoggerFactory loggerFactory,
            CloudinaryService cloudinary,
            FirebaseService firebaseService)
        {
            _ctx = ctx;
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _smsSender = smsSender;
            _logger = loggerFactory.CreateLogger<AccountController>();
            _cloudinary = cloudinary;
            _firebaseService = firebaseService;
        }
        
        [HttpGet]
        public async Task<IActionResult> BuyEventTickets(string id, [FromQuery] string botUserId)
        {
            Event eevent = await _ctx.Events
                .Include(e => e.Bot)
                    .ThenInclude(b => b.Company)
                .Where(e => e.Id == id)
                .FirstOrDefaultAsync();
            if (eevent.Status == EventStatus.Started)
            {
                return View(new PayViewModel
                {
                    BotId = eevent.BotId,
                    BotName = eevent.Bot.Name,
                    CompanyName = eevent.Bot.Company.Name,
                    EventId = eevent.Id,
                    BotUserId = botUserId
                });
            }
            else {
                return RedirectToAction("Index", "Home");
            }
        }
        
        [HttpPost]
        public async Task<IActionResult> BuyEventTickets(BuyEventTicketsViewModel vm, [FromQuery] string botUserId)
        {
            try
            {
                Event eevent = await _ctx.Events
                    .Include(e => e.Bot)
                        .ThenInclude(b => b.Company)
                            .ThenInclude(c => c.Admin)
                    .Where(e => e.Id == vm.EventId)
                    .SingleOrDefaultAsync();

                decimal total = 0;
                foreach (ItemViewModel itemvm in vm.Items)
                {
                    if (itemvm.Quantity > 0)
                    {
                        Item item = await _ctx.Items.SingleOrDefaultAsync(i => i.Id == itemvm.Id);
                        total += (itemvm.Quantity * item.Price);
                    }
                }
                total = total * 100;
                int cent = Convert.ToInt32(total);
                string result = "";
                result = await StripeServices.StripePayment(eevent.Bot.Company.Admin.StripeConnectId, vm.StripeTransactionId, cent, "TestPayment for testing1234567890");
                JObject jObject = JObject.Parse(result);
                var ErrorCheck = jObject["error"];
                if (ErrorCheck == null)
                {
                    ModelState.Clear();
                    var StripeReceiptId = jObject["id"].ToString();

                    string msg = "You have purchase: <br/>";
                    foreach (ItemViewModel itemvm in vm.Items)
                    {
                        if (itemvm.Quantity > 0)
                        {
                            Item item = await _ctx.Items.SingleOrDefaultAsync(i => i.Id == itemvm.Id);
                            string transactionId = Guid.NewGuid().ToString();
                            DateTimeOffset createdOn = DateTimeOffset.UtcNow;
                            BotTransaction botTransaction = new BotTransaction();
                            botTransaction.TransactionId = transactionId;
                            botTransaction.BotId = eevent.BotId;
                            botTransaction.CompanyId = eevent.Bot.CompanyId;
                            botTransaction.CompanyName = eevent.Bot.Company.Name;
                            botTransaction.AdminId = eevent.Bot.Company.Admin.Id;
                            botTransaction.AdminName = $"{eevent.Bot.Company.Admin.FirstName} {eevent.Bot.Company.Admin.LastName}";
                            botTransaction.Status = BotTransactionStatus.Completed;
                            botTransaction.StripeReceiptId = StripeReceiptId;
                            botTransaction.ItemId = item.Id;
                            botTransaction.ItemName = item.Name;
                            botTransaction.Quantity = itemvm.Quantity;
                            botTransaction.Amount = (itemvm.Quantity * item.Price);
                            _ctx.BotTransactions.Add(botTransaction);

                            msg += " " + itemvm.Quantity + " x " + item.Name + " <br/>";
                            msg += "Transaction ID: " + botTransaction.TransactionId + " <br/>";

                        }
                    }
                    msg += "Please show the ticket at the event! <br/>";
                    msg += "The event will be held on " + eevent.Start.UtcDateTime + " and ends on " + eevent.End.UtcDateTime;
                    await _ctx.SaveChangesAsync();
                    await _emailSender.SendCalenderInviteEmailAsync(vm.Email, "Ticket for " + eevent.Name, msg, eevent.Start, eevent.End, eevent.Bot.Company.Name, "");
                    return RedirectToAction(nameof(Bought));
                }
                else
                {
                    ModelState.Clear();
                    string msg = (string)ErrorCheck.SelectToken("message");
                    //Index("testtest", msg)            
                    TempData["ToastType"] = "is-danger";
                    TempData["Toast"] = $"{msg}";

                    return RedirectToAction(nameof(BuyEventTickets));

                }
            }
            catch (Exception err) {
                TempData["ToastType"] = "is-danger";
                TempData["Toast"] = $"Something went wrong! Please try again!";
                return RedirectToAction(nameof(BuyEventTickets));
            }
        }

        [HttpGet]
        public IActionResult Bought(string id)
        {
            return View();
        }

        [HttpGet]
        public IActionResult IFramePaymentDetails()
        {
            return View();
        }

    }
}

Views/Payment/Bought.cshtml
@model PayViewModel
@{
    ViewData["Title"] = "Reciept";
}

@section styles {

}
    <script src="https://js.stripe.com/v3/"></script>

<section class="section">
    <div class="container">
        <p>Thank you for purchasing! </p>
        <p>Please check your email for an e-ticket!</p>
        <p>Show the e-ticket at the event and you're in!</p>
        <p>Have a good day!</p>
    </div>
</section>

@section scripts {
    <script>
        let app = new Vue({
            el: "#app",
            data() {
                return {
                    data: [],
                    total: 0,
                    loading: false
                }
            }
        });

    </script>
}

Views/Payment/BuyEventTickets.cshtml
@model PayViewModel
@{
    ViewData["Title"] = "Pay";
}

@section styles {

    <style>
        button {
            width: 100%;
        }
    </style>
}
    <script src="https://js.stripe.com/v3/"></script>

<section class="section">
    <div class="container">
        <p class="title">@Model.BotName</p>
        <p class="subtitle">@Model.CompanyName</p>

        <form id="mainForm" asp-controller="Payment" asp-action="BuyEventTickets" asp-route-botUserId="@Model.BotUserId">
            <b-table :data="data"
                     :loading="loading"
                     striped>
                <template v-if="props.row.max>0" slot-scope="props">
                    <b-table-column field="name" label="Name">
                        {{ props.row.name }}<br>
                        {{ props.row.description }}
                    </b-table-column>

                    <b-table-column field="price" label="Price">
                        ${{ props.row.price }}
                    </b-table-column>

                    <b-table-column field="Ticket Left" label="Ticket Left">
                        {{ props.row.max - props.row.sold }} 
                    </b-table-column>

                    <b-table-column field="quantity" label="Quantity">
                        <input type="hidden" :name="`items[${props.index}].id`" :value="props.row.id">
                        <b-input :name="`items[${props.index}].quantity`"
                                 type="number"
                                 v-model="props.row.quantity" v-bind:max="props.row.max - props.row.sold">
                        </b-input>
                    </b-table-column>

                    <b-table-column field="subtotal" label="Subtotal">
                        ${{ props.row.quantity * props.row.price }}
                    </b-table-column>
                </template>

                <template slot="empty">
                    <section class="section">
                        <div class="content has-text-grey has-text-centered">
                            <p>
                                <b-icon icon="emoticon-sad"
                                        size="is-large">
                                </b-icon>
                            </p>
                            <p>Nothing to buy here.</p>
                        </div>
                    </section>
                </template>
            </b-table>
            <p class="subtitle is-3 is-pulled-right">Total: ${{ totalPrice }}</p>
            <b-input id="StripeHidden" name="StripeTransactionId" type="hidden"></b-input>
            <b-input id="EmailHidden" name="Email" type="hidden"></b-input>
            <b-input id="EventId" name="EventId" type="hidden" value="@Model.EventId"></b-input>
            <div id="finalPay">
                <button type="submit" class="button is-block is-cyan is-large">Pay</button>
            </div>
        </form>
        <div id="nextButton">
            <button type="button" class="button is-block is-cyan is-large" onclick="next()">Next</button>
        </div>
        <form id="form2">
            <div class="field">
                <label class="label">Name</label>
                <div class="control">
                    <input class="input" type="text" id="data-name" placeholder="Name" required>
                </div>
            </div>
            <div class="field">
                <label class="label">Email</label>
                <div class="control">
                    <input id="data-email" class="input" type="email" placeholder="Email" required>
                </div>
            </div>
            <div class="field">
                <label class="label">Address</label>
                <div class="control">
                    <input class="input" type="text" id="data-address" placeholder="Address" required>
                </div>
            </div>
            <div class="field">
                <label class="label">Zipcode</label>
                <div class="control">
                    <input class="input" type="number" id="data-zip" placeholder="Zipcode" required>
                </div>
            </div>
            <div class="field">
                <label class="label">Card Details</label>
                <div id="example1-card"></div>
            </div>
            <br />

            <button type="submit" class="button is-block is-cyan is-large">Next</button>
            <br />
            <div id="goBackButton">
                <button type="button" class="button is-block is-cyan is-large" onclick="goBackb()">Back</button>
            </div>
        </form>
        <div  id="loading">
            <img style="width:40%; margin-left:30%; margin-right:25%;" src="~/image/loading.gif" />
        </div>
    </div>
</section>

@section scripts {
    <script>
        let app = new Vue({
            el: "#app",
            data() {
                return {
                    data: [],
                    total: 0,
                    loading: false
                }
            },
            methods: {
                /*
                 * Load async data
                 */
                loadAsyncData() {
                    this.loading = true
                    axios.get(`/local/Payment/GetEventTickets/@Model.EventId`)
                        .then(({ data }) => {
                            this.data = data;
                            this.loading = false;
                        })
                        .catch((error) => {
                            this.data = []
                            this.total = 0
                            this.loading = false
                            throw error
                        })
                }
            },
            mounted() {
                this.loadAsyncData()
            },
            computed: {
                totalPrice() {
                    let sum = 0;
                    for (let i = this.data.length - 1; i >= 0; i--) {
                        sum += this.data[i].quantity * this.data[i].price;
                    }
                    return sum;
                }
            }
        });

        var stripe = Stripe('pk_test_OexCkbFIAvIVWTy9f5riCBJP');

        var elements = stripe.elements({
            fonts: [
                {
                    cssSrc: 'https://fonts.googleapis.com/css?family=Roboto',
                },
            ],
            // Stripe's examples are localized to specific languages, but if
            // you wish to have Elements automatically detect your user's locale,
            // use `locale: 'auto'` instead.
            locale: window.__exampleLocale
        });

        var card = elements.create('card', {
            iconStyle: 'solid',
            style: {
                base: {
                    iconColor: '#01C4A7',
                    color: '#000000',
                    fontWeight: 500,
                    fontFamily: 'Roboto, Open Sans, Segoe UI, sans-serif',
                    fontSize: '25px',
                    fontSmoothing: 'antialiased',

                    ':-webkit-autofill': {
                        color: '#000000',
                    },
                    '::placeholder': {
                        color: '#01C4A7',
                    },
                },
                invalid: {
                    iconColor: '#FF3860',
                    color: '#FF3860',
                },
            },
        });
        card.mount('#example1-card');

        var finalPay = document.getElementById('finalPay');
        var form2 = document.getElementById('form2');
        var mainForm = document.getElementById('mainForm');
        var nextButton = document.getElementById('nextButton');
        var goBack = document.getElementById('goBack');
        var loading = document.getElementById('loading');

        var StripeHidden = document.getElementById('StripeHidden');
        var EmailHidden = document.getElementById('EmailHidden');

        function InitialHide() {
            finalPay.style.display = 'none';
            form2.style.display = 'none';
            loading.style.display = 'none';
        }
        InitialHide();

        function next() { 
            loading.style.display = 'none';
            mainForm.style.display = 'none';
            nextButton.style.display = 'none';
            form2.style.display = '';
        }

        function goBackb() {
            mainForm.style.display = '';
            nextButton.style.display = '';
            form2.style.display = 'none';
            loading.style.display = 'none';
        }

        function showLoading() { 
            loading.style.display = '';
            mainForm.style.display = 'none';
            nextButton.style.display = 'none';
            form2.style.display = 'none';
        }
        function showLastStep() {
            finalPay.style.display = '';
            form2.style.display = 'none';
            loading.style.display = 'none';
            nextButton.style.display = 'none';
            mainForm.style.display = '';
        }
        form2.addEventListener('submit', function (e) {
            e.preventDefault();
            showLoading();
            try {
                // Gather additional customer data we may have collected in our form.
                var name = form2.querySelector('#data-name');
                var address1 = form2.querySelector('#data-address');
                var zip = form2.querySelector('#data-zip');
                var email = form2.querySelector('#data-email');
                var additionalData = {
                    name: name ? name.value : undefined,
                    address_line1: address1 ? address1.value : undefined,
                    address_zip: zip ? zip.value : undefined,
                };
                
                // Use Stripe.js to create a token. We only need to pass in one Element
                // from the Element group in order to create a token. We can also pass
                // in the additional customer data we collected in our form.
                stripe.createToken(card, additionalData).then(function (result) {

                    if (result.token) {
                        // If we received a token, send token over to server
                        var token = result.token.id;
                        //var transactionID = document.getElementById('TransactionID').innerHTML;
                        StripeHidden.value = token;
                        EmailHidden.value = email.value;
                        showLastStep();
                    } else {
                        toaster.$toast.open('Please check your credit card number!');
                        next();
                    }
                })
            } catch (err) {
                toaster.$toast.open('Please check your credit card number!');
                next();
            }
        });
        mainForm.addEventListener('submit', function (e) {
            showLoading();
            return true;
         })
    </script>
}

Views/Payment/IFramePaymentDetails.cshtml
<script src="https://js.stripe.com/v3/"></script>

<div class="content">
    <h3 class="title has-text-grey">Credit Card Details</h3>
    <form onsubmit="loadStripe(); return false;" id="cardForm">
        <div class="field">
            <label class="label">Name</label>
            <div class="control">
                <input class="input" type="text" id="data-name" placeholder="Name" required>
            </div>
        </div>
        <div class="field">
            <label class="label">Address</label>
            <div class="control">
                <input class="input" type="text" id="data-address" placeholder="Address" required>
            </div>
        </div>
        <div class="field">
            <label class="label">Zipcode</label>
            <div class="control">
                <input class="input" type="number" id="data-zip" placeholder="Zipcode" required>
            </div>
        </div>
        <div class="field">
            <label class="label">Card Details</label>
            <div id="card_det">
            </div>
        </div>
        <br />

        <button type="submit" style="width:100%;" class="button is-block is-cyan is-large">Submit</button>
        <br />
        <button type="button" id="skipBtn" style="width:100%;" onclick="skip();" class="button is-block is-cyan is-large">Skip</button>
        <br />

    </form>

    <div id="loading">
        <img style="width:40%; margin-left:30%; margin-right:25%;" src="~/image/loading.gif" />
    </div>
</div>
<script>
    var stripe = Stripe('pk_test_OexCkbFIAvIVWTy9f5riCBJP');
    var elements = stripe.elements({
        fonts: [
            {
                cssSrc: 'https://fonts.googleapis.com/css?family=Roboto',
            },
        ],
        // Stripe's examples are localized to specific languages, but if
        // you wish to have Elements automatically detect your user's locale,
        // use `locale: 'auto'` instead.
        locale: window.__exampleLocale
    });

    var card = elements.create('card', {
        iconStyle: 'solid',
        style: {
            base: {
                iconColor: '#01C4A7',
                color: '#000000',
                fontWeight: 500,
                fontFamily: 'Roboto, Open Sans, Segoe UI, sans-serif',
                fontSize: '25px',
                fontSmoothing: 'antialiased',

                ':-webkit-autofill': {
                    color: '#000000',
                },
                '::placeholder': {
                    color: '#01C4A7',
                },
            },
            invalid: {
                iconColor: '#FF3860',
                color: '#FF3860',
            },
        },
    });

    card.mount('#card_det');

    var cardForm = document.getElementById('cardForm');
    var loading = document.getElementById('loading');
    loading.style.display = 'none';
    get();
    function showLoading() {
        loading = document.getElementById('loading');
        loading.style.display = '';
        cardForm = document.getElementById('cardForm');
        cardForm.style.display = 'none';
    }
    function hideLoading() {
        loading = document.getElementById('loading');
        loading.style.display = 'none';
        cardForm = document.getElementById('cardForm');
        cardForm.style.display = '';
    }

    function skip(){
        showLoading();
        parent.submitForm();
    }

    function toHide() { 
        var skipBtn = document.getElementById('skipBtn');
        skipBtn.style.visibility = 'hidden';
    }

    function loadStripe(){
        //e.preventDefault();
        cardForm = document.getElementById('cardForm');
        showLoading();
        try {
            // Gather additional customer data we may have collected in our form.
            var name = cardForm.querySelector('#data-name');
            var address1 = cardForm.querySelector('#data-address');
            var zip = cardForm.querySelector('#data-zip');
            var additionalData = {
                name: name ? name.value : undefined,
                address_line1: address1 ? address1.value : undefined,
                address_zip: zip ? zip.value : undefined,
            };

            //console.dir(card)
            // Use Stripe.js to create a token. We only need to pass in one Element
            // from the Element group in order to create a token. We can also pass
            // in the additional customer data we collected in our form.
            stripe.createToken(card, additionalData).then(function (result) {

                if (result.token) {
                    // If we received a token, send token over to server
                    var token = result.token.id;
                    parent.passer(token);

                } else {
                    toaster.$toast.open('Please check your credit card number!');
                }
            })
        } catch (err) {
            toaster.$toast.open('Please check your credit card number!');
        }
    };

    function get(){
        var checker = getQueryVariable('toHide');
        console.log(checker);
        if(checker){
            toHide();
        }
    }

    function getQueryVariable(variable)
    {
           var query = window.location.search.substring(1);
           var vars = query.split("&");
           for (var i=0;i<vars.length;i++) {
                   var pair = vars[i].split("=");
                   if(pair[0] == variable){return pair[1];}
           }
           return(false);
    }
</script>