Models/Workspace/PublishBotViewModel.cs
using System;
namespace NyxWebPortal.Models.Workspace
{
    public class PublishBotViewModel
    {
        public string TelegramApiToken { get; set; }
        public string FacebookPageId { get; set; }
        public string FacebookAppId { get; set; }
        public string FacebookAppSecret { get; set; }
        public string FacebookPageAccessToken { get; set; }
    }
}

Models/Workspace/RegisterCustomerSupportViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace NyxWebPortal.Models.Workspace
{
    public class RegisterCustomerSupportViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        
        [Required]
        public string FirstName { get; set; }
        
        [Required]
        public string LastName { get; set; }
        
        [Required]
        public string DOB { get; set; }
        
        public IFormFile ProfileImg { get; set; }
        
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
    }
}

Models/Workspace/SupportingBotViewModel.cs
using System;
namespace NyxWebPortal.Models.Workspace
{
    public class SupportingBotViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Url { get; set; }
        public string PlanId { get; set; }
        public bool IsSupported { get; set; }
    }
}

Controllers/CustomerSupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using NyxDatabase.Data;
using NyxWebPortal.Services.Firebase;
using NyxDatabase.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using NyxWebPortal.Utils;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace NyxWebPortal.Controllers
{

    [Authorize(Roles = AccountController.companyCustomerSupportRole+","+AccountController.companyAdminRole)]
    public class CustomerSupportController : Controller
    {
        private readonly NyxDbContext _ctx;
        private readonly UserManager<NyxCustomer> _userManager;
        private readonly FirebaseService _firebaseService;

        public CustomerSupportController(
            NyxDbContext ctx,
            UserManager<NyxCustomer> userManager,
            FirebaseService firebaseService)
        {
            _ctx = ctx;
            _userManager = userManager;
            _firebaseService = firebaseService;
        }
        
        public async Task<IActionResult> Index()
        {
            CompanyAdmin companyCustomerSupport = await this.GetCompanyAdminAsync(_userManager, User);
            List<Bot> bots = new List<Bot>();
                bots = await _ctx.Bots
                   .Where(b => b.CompanyId == companyCustomerSupport.CompanyId)
                   .ToListAsync();
            return View(bots);
        }
        
        public async Task<IActionResult> Chat()
        {
            NyxCustomer currentUser = await _userManager.GetUserAsync(User);
            string customToken = await _firebaseService.CustomTokenAsync(currentUser._FirebaseRefreshToken);

            @ViewData["customToken"] = customToken;
            ViewData["current_user"] = currentUser.Email;

            return View();
        }
        public ActionResult EditQuestion()
        {
            return View();
        }
        public ActionResult EditSmallTalk()
        {
            return View();
        }

        [HttpGet("/[controller]/[action]/{botId}")]
        public async Task<IActionResult> getBotIntent(string botId)
        {
            HttpClient client = new HttpClient
            {
                BaseAddress = new Uri("https://nyxdata-v2.firebaseio.com/Bot/"),
            };
            try
            {
                var response = await client.GetAsync(botId + "/Intents.json");
                var result = response.Content.ReadAsStringAsync().Result;
                var jsonResult = JsonConvert.DeserializeObject(result);
                return new JsonResult(jsonResult);
            }
            catch (Exception e)
            {
                return BadRequest(e);
            }
        }
        [HttpPut("/[controller]/[action]/{botId}")]
        // you guys can change the JArray to models as soon as you guys figure out the model thing in the 
        // bot repo problem
        public async Task<IActionResult> updateBotIntent(string botId, [FromBody]Newtonsoft.Json.Linq.JArray value)
        {
            var resrponds = Request;
            HttpClient client = new HttpClient
            {
                BaseAddress = new Uri("https://nyxdata-v2.firebaseio.com/Bot/"),
            };
            try
            {
                string data = JsonConvert.SerializeObject(value);
                var content = new StringContent(data, Encoding.UTF8, "application/json");
                var response = await client.PutAsync(botId + "/Intents.json", content);
                bool status = response.IsSuccessStatusCode;
                if (status)
                {
                    return Ok();
                }
                else
                {
                    return BadRequest();
                }
            }
            catch (Exception e)
            {
                return BadRequest(e);
            }
        }

        [HttpGet("/[controller]/[action]/{botId}")]
        public async Task<IActionResult> getSmallTalk(string botId)
        {
            HttpClient client = new HttpClient
            {
                BaseAddress = new Uri("https://nyxdata-v2.firebaseio.com/Bot/"),
            };
            try
            {
                var response = await client.GetAsync(botId + "/SmallTalk.json");
                var result = response.Content.ReadAsStringAsync().Result;
                var jsonResult = JsonConvert.DeserializeObject(result);
                return new JsonResult(jsonResult);
            }
            catch (Exception e)
            {
                return BadRequest(e);
            }
        }

        [HttpPut("/[controller]/[action]/{botId}")]
        // you guys can change the JArray to models as soon as you guys figure out the model thing in the 
        // bot repo problem
        public async Task<IActionResult> updateSmallTalk(string botId, [FromBody]Newtonsoft.Json.Linq.JArray value)
        {
            var resrponds = Request;
            HttpClient client = new HttpClient
            {
                BaseAddress = new Uri("https://nyxdata-v2.firebaseio.com/Bot/"),
            };
            try
            {
                string data = JsonConvert.SerializeObject(value);
                var content = new StringContent(data, Encoding.UTF8, "application/json");
                var response = await client.PutAsync(botId + "/SmallTalk.json", content);
                bool status = response.IsSuccessStatusCode;
                if (status)
                {
                    return Ok();
                }
                else
                {
                    return BadRequest();
                }
            }
            catch (Exception e)
            {
                return BadRequest(e);
            }
        }
    }
}

Controllers/WorkspaceController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NyxDatabase.Data;
using NyxDatabase.Models;
using NyxDatabase.Models.ManyToMany;
using NyxWebPortal.Models.Workspace;
using NyxWebPortal.Services;
using NyxWebPortal.Services.Firebase;
using NyxWebPortal.Utils;
using NyxBot.Diagnostics;
using System.Net;
using System.IO;
using Newtonsoft.Json.Linq;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace NyxWebPortal.Controllers
{
    [Authorize(Roles = AccountController.companyAdminRole)]
    public class WorkspaceController : Controller
    {
        private readonly UserManager<NyxCustomer> _userManager;
        private readonly NyxDbContext _ctx;
        private readonly CloudinaryService _cloudinary;
        private readonly FirebaseService _firebaseService;
        private readonly IEmailSender _emailSender;
        private readonly ILogger _logger;

        public WorkspaceController(
            UserManager<NyxCustomer> userManager,
            NyxDbContext ctx,
            CloudinaryService cloudinary,
            FirebaseService firebaseService,
            IEmailSender emailSender,
            ILoggerFactory loggerFactory)
        {
            _userManager = userManager;
            _ctx = ctx;
            _cloudinary = cloudinary;
            _firebaseService = firebaseService;
            _emailSender = emailSender;
            _logger = loggerFactory.CreateLogger<AccountController>();
        }

        public const string BotCloudinaryFolder = "bot";

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> CreateBot()
        {
            BotViewModel vm = new BotViewModel();
            vm.Plans = await _ctx.Plans.ToListAsync();
            vm.Countries = await _ctx.Countries.Select(c => c.Id).ToListAsync();
            vm.StripeCustomerId = (await this.GetCompanyAdminAsync(_userManager, User)).StripeCustomerId;
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateGrcBot(GrcBotViewModel vm)
        {
            CompanyAdmin companyAdmin = await this.GetCompanyAdminAsync(_userManager, User);
            string stripeBotSubId = "";

            BotViewModel toSendBack = new BotViewModel();
            toSendBack.Plans = await _ctx.Plans.ToListAsync();
            toSendBack.Countries = await _ctx.Countries.Select(c => c.Id).ToListAsync();
            toSendBack.StripeCustomerId = (await this.GetCompanyAdminAsync(_userManager, User)).StripeCustomerId;

            if (vm.StripeCustomerId != "" && vm.StripeCustomerId != null)
            {
                if (companyAdmin.StripeCustomerId != vm.StripeCustomerId)
                {
                    string result = await StripeServices.CreateCustomer(vm.StripeCustomerId, companyAdmin.Email);
                    JObject jObject = JObject.Parse(result);
                    var ErrorCheck = jObject["error"];
                    if (ErrorCheck == null)
                    {
                        companyAdmin.StripeCustomerId = jObject["id"].ToString();
                        _ctx.CompanyAdmins.Update(companyAdmin);

                        result = await StripeServices.Subscribe(companyAdmin.StripeCustomerId, vm.StripePlanId);
                        jObject = JObject.Parse(result);
                        ErrorCheck = jObject["error"];
                        if (ErrorCheck == null)
                        {
                            stripeBotSubId = jObject["id"].ToString();
                        }
                        else
                        {

                            TempData["Toast"] = $"Something went worng with Stripe!";
                            TempData["ToastType"] = "is-success";
                            return RedirectToAction(nameof(CreateBot));
                        }
                    }
                    else
                    {
                        TempData["Toast"] = $"Something went worng with Stripe!";
                        TempData["ToastType"] = "is-success";
                        return RedirectToAction(nameof(CreateBot));
                    }

                }
                else
                {
                    string result = await StripeServices.Subscribe(companyAdmin.StripeCustomerId, vm.StripePlanId);
                    JObject jObject = JObject.Parse(result);
                    var ErrorCheck = jObject["error"];

                    ErrorCheck = jObject["error"];
                    if (ErrorCheck == null)
                    {
                        stripeBotSubId = jObject["id"].ToString();
                    }
                    else
                    {
                        TempData["Toast"] = $"Something went worng with your Stripe!";
                        TempData["ToastType"] = "is-danger";
                        return RedirectToAction(nameof(CreateBot));
                    }

                }
            }
            else {
                TempData["Toast"] = $"Something went worng!";
                TempData["ToastType"] = "is-danger";
                return RedirectToAction(nameof(CreateBot));
            }

            // Add to db
            GRCBot grcBot = new GRCBot();
            grcBot.Id = Utils.RandomGenerator.GetStringAlphanumeric(16);
            grcBot.Name = vm.Name;
            grcBot.Type = vm.Type;
            grcBot.PlanId = vm.PlanId;
            grcBot.Address = new Address();
            grcBot.Address.BotId = grcBot.Id;
            grcBot.Address.AddressLine1 = vm.AddressLine1;
            grcBot.Address.AddressLine2 = vm.AddressLine2;
            grcBot.Address.PostalCode = vm.PostalCode;
            grcBot.CompanyId = companyAdmin.CompanyId;
            grcBot.VolunteerUrl = vm.VolunteerUrl;
            grcBot.WelcomeMessage = vm.WelcomeMessage;
            grcBot.NoAnswerFoundMessage = vm.NoAnswerFoundMessage;
            grcBot.RequestContactDetailsMessage = vm.RequestContactDetailsMessage;
            grcBot.UserAgreeContactMessage = vm.UserAgreeContactMessage;
            grcBot.UserDisagreeContactMessage = vm.UserDisagreeContactMessage;
            grcBot.UserSwearMessage = vm.UserSwearMessage;
            grcBot.AskUserUsefulMessage = vm.AskUserUsefulMessage;
            grcBot.AskUserUsefulPercentage = vm.AskUserUsefulPercentage;
            grcBot.Status = BotStatus.CollectedAdminData;
            grcBot.TeamInfoImageUrl = await _cloudinary.UploadAsync(grcBot.Id, grcBot.Id, grcBot.Id, vm.TeamImage);
            grcBot.StripeSubscriptionId = stripeBotSubId;
            grcBot._Active = false;
            grcBot._CreatedOn = DateTime.UtcNow;
            await _ctx.GRCBots.AddAsync(grcBot);

            // Create firebase and config firebase whitelist
            await _firebaseService.CreateBotAsync(companyAdmin, grcBot);

            await _ctx.SaveChangesAsync();

            // Redirect to GRC edit page
            return RedirectToAction(nameof(Details), new { id = grcBot.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateTeamInfo(string BotId, GrcBotViewModel vm){

            if (!ModelState.IsValid)
            {
                return View();
            }

            CompanyAdmin companyAdmin = await this.GetCompanyAdminAsync(_userManager, User);
            GRCBot bot = await _ctx.GRCBots.SingleOrDefaultAsync(b => b.Id == BotId && b.CompanyId == companyAdmin.CompanyId);

            if (bot == null)
                return RedirectToAction(nameof(Bots));

            bot.TeamInfoImageUrl = await _cloudinary.UploadAsync(BotId, BotId, BotId, vm.TeamImage);

            await _ctx.SaveChangesAsync();

            return RedirectToAction(nameof(Details), new { id = BotId });
        }
        //[HttpPost]
        //public IActionResult CreateShopBot(ShopBotViewModel vm)
        //{

        //    return View();
        //}

        [HttpGet]
        public async Task<IActionResult> Bots()
        {
            CompanyAdmin companyAdmin = await this.GetCompanyAdminAsync(_userManager, User);
            List<Bot> bots = new List<Bot>();
                bots = await _ctx.Bots
                   .Where(b => b.CompanyId == companyAdmin.CompanyId)
                   .ToListAsync();
            //Bot b = new Bot();
            return View(bots);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            CompanyAdmin companyAdmin = await this.GetCompanyAdminAsync(_userManager, User);
            Bot bot = await _ctx.GRCBots.SingleOrDefaultAsync(b => b.Id == id && b.CompanyId == companyAdmin.CompanyId);

            if (bot == null)
                return RedirectToAction(nameof(Bots));

            if (bot is GRCBot)
            {
                GRCBot grcBot = await _ctx.GRCBots
                    .Include(b => b.Plan)
                    .Include(b => b.Address)
                    .SingleOrDefaultAsync(b => b.Id == id && b.CompanyId == companyAdmin.CompanyId);
                return View("ViewGrc", grcBot);
            }

            return null;
        }

        [HttpGet]
        public async Task<IActionResult> EditBotDetails(string id)
        {
            CompanyAdmin companyAdmin = await this.GetCompanyAdminAsync(_userManager, User);

            Bot bot = await _ctx.Bots
                .SingleOrDefaultAsync(b => b.Id == id && b.CompanyId == companyAdmin.CompanyId);

            if (bot == null)

Views/Workspace/AddBotEventItem.cshtml
@model NyxDatabase.Models.Event

@{
    ViewData["Title"] = "Add Ticket";
}

<section class="section">
    <div class="container">
        <form asp-controller="Workspace"
              asp-action="AddBotEventItem"
              asp-route-id="@Model.Id">

            <b-field label="Name">
                <b-input name="Name"></b-input>
            </b-field>

            <b-field label="Description">
                <b-input name="Description"></b-input>
            </b-field>

            <b-field label="Number of tickets bot has">
                <b-input type="number" v-model="Ticket" pattern="([0-9])" name="NumberOfTickets"></b-input>
                <p class="control">
                    <span class="button is-static">ticket(s)</span>
                </p>
            </b-field>

            <b-field label="Ticket Price">
                <p class="control">
                    <span class="button is-static">$</span>
                </p>
                <b-input type="number" name="TicketPrice"></b-input>
            </b-field>
            <b-field>
                <b-checkbox name="IsReservable`" v-model="IsReservable" native-value="true">Reservable</b-checkbox>
            </b-field>
            <b-field v-if="IsReservable" label="Number of tickets that can be reserved per order">
                <b-input type="number" pattern="([0-9])" :max="Ticket" name="MaxReservablePerOrder"></b-input>
                <p class="control">
                    <span class="button is-static">ticket(s)</span>
                </p>
            </b-field>
            <b-field v-if="IsReservable" label="Number of days tickets can be reserved">
                <b-input type="number" pattern="([0-9])" name="MaxReserveHoldDays"></b-input>
                <p class="control">
                    <span class="button is-static">day(s)</span>
                </p>
            </b-field>
            <b-field label="Ticket Sale Start Date and Time">
                <b-field>
                    <flat-pickr placeholder="Ticket Sale Start Date and Time" value="" name="StartDateTime" :config="ExStartDate" @@on-change="onStartChange" class="input"></flat-pickr>
                </b-field>
            </b-field>
            <b-field label="Ticket Sale End Date and Time">
                <b-field>
                    <flat-pickr placeholder="Ticket Sale End Date and Time" value="" name="EndDateTime" :config="ExEndDate" class="input"></flat-pickr>
                </b-field>
            </b-field>
            <button type="submit">Add</button>
        </form>
    </div>
</section>

@section scripts {

    <link href="https://unpkg.com/flatpickr@4/dist/flatpickr.min.css" rel="stylesheet">
    <script src="https://unpkg.com/flatpickr@4/dist/flatpickr.min.js"></script>
    <script src="https://unpkg.com/vue-flatpickr-component@7"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.min.js"></script>
    <script>
        Vue.component('flat-pickr', VueFlatpickr);
        let app = new Vue({
            el: '#app',
            data() {
                return {
                    Ticket: 0,
                    IsReservable: false,
                    datePickerConfig:
                    {
                        minDate: "today",
                        enableTime: true,
                        dateFormat: "m/d/Y H:i"
                    },
                    ExStartDate: {
                        minDate: "today",
                        enableTime: true,
                        dateFormat: "m/d/Y H:i"
                    },
                    ExEndDate: {
                        minDate: "today",
                        enableTime: true,
                        dateFormat: "m/d/Y H:i"
                    },
                    onStartChange: function (selectedDates, dateStr, instance) {
                        app.ExEndDate.minDate = dateStr;
                    },
                }
            }
        })

    </script>
}

Views/Workspace/Bots.cshtml
@{
    ViewData["Title"] = "Your Bots";
}

<section class="section">
    <div class="container">
        <a asp-controller="Workspace" asp-action="CreateBot" class="button">Create bot</a>
        <div class="columns is-multiline">
            @foreach (var bot in Model)
            {
                <div class="column has-text-centered is-one-quarter">
                    <div class="card">
                        <div class="card-image">
                            <figure class="image is-4by3">
                                <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
                            </figure>
                        </div>
                        <div class="card-content">
                            <div class="content">
                                <p class="title">@bot.Name</p>
                                <p class="subtitle">@bot.Type</p>
                            </div>
                        </div>
                        <footer class="card-footer">
                            <a asp-controller="Analytics" asp-action="Index" asp-route-id="@bot.Id" class="card-footer-item">Analytics</a>
                            <a asp-controller="Workspace" asp-action="Details" asp-route-id="@bot.Id" class="card-footer-item">Details</a>

                            <div class="dropdown is-hoverable is-right card-footer-item">
                                <div class="dropdown-trigger">
                                    Support<i class="mdi mdi-chevron-down"></i>
                                </div>
                                <div class="dropdown-menu" id="dropdown-menu4" role="menu">
                                    <div class="dropdown-content">
                                        <a asp-controller="CustomerSupport" asp-action="Chat" asp-route-id="@bot.Id" class="dropdown-item">Chat</a>
                                        <a asp-controller="CustomerSupport" asp-action="EditQuestion" asp-route-id="@bot.Id" class="dropdown-item">Edit Q&A</a>
                                        <a asp-controller="CustomerSupport" asp-action="EditSmallTalk" asp-route-id="@bot.Id" class="dropdown-item">Edit Small Talk</a>
                                    </div>
                                </div>
                            </div>

                            <div class="dropdown is-hoverable is-right card-footer-item">
                                <div class="dropdown-trigger">
                                    Admin Panel<i class="mdi mdi-chevron-down"></i>
                                </div>
                                <div class="dropdown-menu" id="dropdown-menu4" role="menu">
                                    <div class="dropdown-content">
                                        <a asp-controller="Workspace" asp-action="ViewVolunteers" asp-route-id="@bot.Id" class="navbar-item">View All Volunteers</a>
                                        <a asp-controller="Workspace" asp-action="ViewGeneralFeedback" asp-route-id="@bot.Id" class="navbar-item">View All General Feedback</a>
                                    </div>
                                </div>
                            </div>
                        </footer>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

Views/Workspace/CustomerSupports.cshtml
@{
    ViewData["Title"] = "Customer Supports";
}

<section class="section">
    <a asp-controller="Workspace" asp-action="RegisterCustomerSupport" class="button">Register new customer Support</a>
    <div class="container">
        <b-table
            :data="tables.customerSupports.data"
            :loading="tables.customerSupports.loading"

            paginated
            backend-pagination
            :total="tables.customerSupports.total"
            :per-page="tables.customerSupports.perPage"
            v-on:page-change="onCustomerSupportsPageChange"

            backend-sorting
            :default-sort-direction="tables.customerSupports.defaultSortOrder"
            :default-sort="[tables.customerSupports.sortField, tables.customerSupports.sortOrder]"
            v-on:sort="onCustomerSupportsSort">

            <template slot-scope="props">
                <b-table-column field="firstName" label="First Name" sortable centered>
                    {{ props.row.firstName }}
                </b-table-column>
                
                <b-table-column field="lastName" label="Last Name" sortable centered>
                    {{ props.row.lastName }}
                </b-table-column>

                <b-table-column field="email" label="Email" sortable centered>
                    {{ props.row.email }}
                </b-table-column>
                
                <b-table-column field=" " label="Actions" centered>
                    <a asp-controller="Workspace" asp-action="ViewCustomerSupport" class="button is-cyan">View</a>
                </b-table-column>
            </template>
            
            <template slot="empty">
                <section class="section">
                    <div class="content has-text-grey has-text-centered">
                        <p>
                            <b-icon
                                icon="emoticon-sad"
                                size="is-large">
                            </b-icon>
                        </p>
                        <p>Nothing here.</p>
                    </div>
                </section>
            </template>
        </b-table>
    </div>
</section>

@section scripts {
    <script>
        let app = new Vue({
            el: "#app",
            data() {
                return {
                    tables: {
                        customerSupports: {
                            data: [],
                            total: 0,
                            loading: false,
                            sortField: 'date',
                            sortOrder: 'desc',
                            defaultSortOrder: 'desc',
                            page: 1,
                            perPage: 20
                        }
                    }
                }
            },
            methods: {
                loadCustomerSupportsDataAsync() {
                    let table = this.tables.customerSupports
                    
                    const params = [
                        `sortBy=${table.sortField}.${table.sortOrder}`,
                        `perpage=${table.perPage}`,
                        `page=${table.page}`
                    ].join('&')
                    
                    table.loading = true
                    axios.get(`/local/Workspace/GetCustomerSupports?${params}`)
                        .then(({ data }) => {
                            table.data = []
                            table.total = data.total
                            for (let i = data.customerSupports.length - 1; i >= 0; i--) {
                                let item = data.customerSupports[i]
                                table.data.unshift(item)
                            }
                            table.loading = false
                        })
                        .catch((error) => {
                            table.data = []
                            table.total = 0
                            table.loading = false
                            throw error
                        })
                },
                /*
                 * Handle page-change event
                 */
                onCustomerSupportsPageChange(page) {
                    let table = this.tables.customerSupports
                    table.page = page
                    this.loadCustomerSupportsDataAsync()
                },
                /*
                 * Handle sort event
                 */
                onCustomerSupportsSort(field, order) {
                    let table = this.tables.customerSupports
                    table.sortField = field
                    table.sortOrder = order
                    this.loadCustomerSupportsDataAsync()
                },
            },
            mounted() {
                this.loadCustomerSupportsDataAsync()
            }
        })
    </script>
}

Views/Workspace/Index.cshtml
@{
    ViewData["Title"] = "Dashboard";
}

<section class="section">
    <div class="container">
        <a asp-controller="Workspace" asp-action="Bots" class="button is-outlined is-large">Bots</a>
    </div>
</section>